// AUTO-GENERATED by scripts/generate-brand-icon-index.mjs — do not edit by hand.
// Maps normalized brand icon keys to locally vendored dark/light PNGs,
// replacing the registry.npmmirror.com CDN (blocked by the production CSP).

import ai2ColorDark from './icons/dark/ai2-color.png'
import ai21BrandColorDark from './icons/dark/ai21-brand-color.png'
import aionlabsColorDark from './icons/dark/aionlabs-color.png'
import arceeColorDark from './icons/dark/arcee-color.png'
import baaiDark from './icons/dark/baai.png'
import baichuanColorDark from './icons/dark/baichuan-color.png'
import bailianColorDark from './icons/dark/bailian-color.png'
import bytedanceColorDark from './icons/dark/bytedance-color.png'
import cerebrasBrandColorDark from './icons/dark/cerebras-brand-color.png'
import claudeColorDark from './icons/dark/claude-color.png'
import cohereColorDark from './icons/dark/cohere-color.png'
import deepcogitoColorDark from './icons/dark/deepcogito-color.png'
import deepinfraColorDark from './icons/dark/deepinfra-color.png'
import deeplColorDark from './icons/dark/deepl-color.png'
import deepseekColorDark from './icons/dark/deepseek-color.png'
import doubaoColorDark from './icons/dark/doubao-color.png'
import essentialaiColorDark from './icons/dark/essentialai-color.png'
import fireworksColorDark from './icons/dark/fireworks-color.png'
import geminiColorDark from './icons/dark/gemini-color.png'
import groqDark from './icons/dark/groq.png'
import hunyuanColorDark from './icons/dark/hunyuan-color.png'
import ibmDark from './icons/dark/ibm.png'
import inceptionDark from './icons/dark/inception.png'
import inflectionDark from './icons/dark/inflection.png'
import internlmColorDark from './icons/dark/internlm-color.png'
import jinaDark from './icons/dark/jina.png'
import liquidDark from './icons/dark/liquid.png'
import longcatColorDark from './icons/dark/longcat-color.png'
import metaColorDark from './icons/dark/meta-color.png'
import microsoftColorDark from './icons/dark/microsoft-color.png'
import midjourneyDark from './icons/dark/midjourney.png'
import minimaxColorDark from './icons/dark/minimax-color.png'
import mistralColorDark from './icons/dark/mistral-color.png'
import moonshotDark from './icons/dark/moonshot.png'
import morphColorDark from './icons/dark/morph-color.png'
import nousresearchDark from './icons/dark/nousresearch.png'
import novaDark from './icons/dark/nova.png'
import nvidiaColorDark from './icons/dark/nvidia-color.png'
import openaiDark from './icons/dark/openai.png'
import openrouterDark from './icons/dark/openrouter.png'
import qwenColorDark from './icons/dark/qwen-color.png'
import relaceDark from './icons/dark/relace.png'
import replicateBrandDark from './icons/dark/replicate-brand.png'
import sensenovaBrandColorDark from './icons/dark/sensenova-brand-color.png'
import sparkColorDark from './icons/dark/spark-color.png'
import stabilityColorDark from './icons/dark/stability-color.png'
import stepfunColorDark from './icons/dark/stepfun-color.png'
import togetherBrandColorDark from './icons/dark/together-brand-color.png'
import upstageColorDark from './icons/dark/upstage-color.png'
import wenxinColorDark from './icons/dark/wenxin-color.png'
import xaiDark from './icons/dark/xai.png'
import xiaomimimoDark from './icons/dark/xiaomimimo.png'
import yiColorDark from './icons/dark/yi-color.png'
import zaiDark from './icons/dark/zai.png'
import zhipuColorDark from './icons/dark/zhipu-color.png'
import ai2ColorLight from './icons/light/ai2-color.png'
import ai21BrandColorLight from './icons/light/ai21-brand-color.png'
import aionlabsColorLight from './icons/light/aionlabs-color.png'
import arceeColorLight from './icons/light/arcee-color.png'
import baaiLight from './icons/light/baai.png'
import baichuanColorLight from './icons/light/baichuan-color.png'
import bailianColorLight from './icons/light/bailian-color.png'
import bytedanceColorLight from './icons/light/bytedance-color.png'
import cerebrasBrandColorLight from './icons/light/cerebras-brand-color.png'
import claudeColorLight from './icons/light/claude-color.png'
import cohereColorLight from './icons/light/cohere-color.png'
import deepcogitoColorLight from './icons/light/deepcogito-color.png'
import deepinfraColorLight from './icons/light/deepinfra-color.png'
import deeplColorLight from './icons/light/deepl-color.png'
import deepseekColorLight from './icons/light/deepseek-color.png'
import doubaoColorLight from './icons/light/doubao-color.png'
import essentialaiColorLight from './icons/light/essentialai-color.png'
import fireworksColorLight from './icons/light/fireworks-color.png'
import geminiColorLight from './icons/light/gemini-color.png'
import groqLight from './icons/light/groq.png'
import hunyuanColorLight from './icons/light/hunyuan-color.png'
import ibmLight from './icons/light/ibm.png'
import inceptionLight from './icons/light/inception.png'
import inflectionLight from './icons/light/inflection.png'
import internlmColorLight from './icons/light/internlm-color.png'
import jinaLight from './icons/light/jina.png'
import liquidLight from './icons/light/liquid.png'
import longcatColorLight from './icons/light/longcat-color.png'
import metaColorLight from './icons/light/meta-color.png'
import microsoftColorLight from './icons/light/microsoft-color.png'
import midjourneyLight from './icons/light/midjourney.png'
import minimaxColorLight from './icons/light/minimax-color.png'
import mistralColorLight from './icons/light/mistral-color.png'
import moonshotLight from './icons/light/moonshot.png'
import morphColorLight from './icons/light/morph-color.png'
import nousresearchLight from './icons/light/nousresearch.png'
import novaLight from './icons/light/nova.png'
import nvidiaColorLight from './icons/light/nvidia-color.png'
import openaiLight from './icons/light/openai.png'
import openrouterLight from './icons/light/openrouter.png'
import qwenColorLight from './icons/light/qwen-color.png'
import relaceLight from './icons/light/relace.png'
import replicateBrandLight from './icons/light/replicate-brand.png'
import sensenovaBrandColorLight from './icons/light/sensenova-brand-color.png'
import sparkColorLight from './icons/light/spark-color.png'
import stabilityColorLight from './icons/light/stability-color.png'
import stepfunColorLight from './icons/light/stepfun-color.png'
import togetherBrandColorLight from './icons/light/together-brand-color.png'
import upstageColorLight from './icons/light/upstage-color.png'
import wenxinColorLight from './icons/light/wenxin-color.png'
import xaiLight from './icons/light/xai.png'
import xiaomimimoLight from './icons/light/xiaomimimo.png'
import yiColorLight from './icons/light/yi-color.png'
import zaiLight from './icons/light/zai.png'
import zhipuColorLight from './icons/light/zhipu-color.png'

export type BrandIconVariant = 'dark' | 'light'

export const BRAND_ICONS: Record<string, Record<BrandIconVariant, string>> = {
  'ai2-color': { dark: ai2ColorDark, light: ai2ColorLight },
  'ai21-brand-color': { dark: ai21BrandColorDark, light: ai21BrandColorLight },
  'aionlabs-color': { dark: aionlabsColorDark, light: aionlabsColorLight },
  'arcee-color': { dark: arceeColorDark, light: arceeColorLight },
  baai: { dark: baaiDark, light: baaiLight },
  'baichuan-color': { dark: baichuanColorDark, light: baichuanColorLight },
  'bailian-color': { dark: bailianColorDark, light: bailianColorLight },
  'bytedance-color': { dark: bytedanceColorDark, light: bytedanceColorLight },
  'cerebras-brand-color': {
    dark: cerebrasBrandColorDark,
    light: cerebrasBrandColorLight,
  },
  'claude-color': { dark: claudeColorDark, light: claudeColorLight },
  'cohere-color': { dark: cohereColorDark, light: cohereColorLight },
  'deepcogito-color': {
    dark: deepcogitoColorDark,
    light: deepcogitoColorLight,
  },
  'deepinfra-color': { dark: deepinfraColorDark, light: deepinfraColorLight },
  'deepl-color': { dark: deeplColorDark, light: deeplColorLight },
  'deepseek-color': { dark: deepseekColorDark, light: deepseekColorLight },
  'doubao-color': { dark: doubaoColorDark, light: doubaoColorLight },
  'essentialai-color': {
    dark: essentialaiColorDark,
    light: essentialaiColorLight,
  },
  'fireworks-color': { dark: fireworksColorDark, light: fireworksColorLight },
  'gemini-color': { dark: geminiColorDark, light: geminiColorLight },
  groq: { dark: groqDark, light: groqLight },
  'hunyuan-color': { dark: hunyuanColorDark, light: hunyuanColorLight },
  ibm: { dark: ibmDark, light: ibmLight },
  inception: { dark: inceptionDark, light: inceptionLight },
  inflection: { dark: inflectionDark, light: inflectionLight },
  'internlm-color': { dark: internlmColorDark, light: internlmColorLight },
  jina: { dark: jinaDark, light: jinaLight },
  liquid: { dark: liquidDark, light: liquidLight },
  'longcat-color': { dark: longcatColorDark, light: longcatColorLight },
  'meta-color': { dark: metaColorDark, light: metaColorLight },
  'microsoft-color': { dark: microsoftColorDark, light: microsoftColorLight },
  midjourney: { dark: midjourneyDark, light: midjourneyLight },
  'minimax-color': { dark: minimaxColorDark, light: minimaxColorLight },
  'mistral-color': { dark: mistralColorDark, light: mistralColorLight },
  moonshot: { dark: moonshotDark, light: moonshotLight },
  'morph-color': { dark: morphColorDark, light: morphColorLight },
  nousresearch: { dark: nousresearchDark, light: nousresearchLight },
  nova: { dark: novaDark, light: novaLight },
  'nvidia-color': { dark: nvidiaColorDark, light: nvidiaColorLight },
  openai: { dark: openaiDark, light: openaiLight },
  openrouter: { dark: openrouterDark, light: openrouterLight },
  'qwen-color': { dark: qwenColorDark, light: qwenColorLight },
  relace: { dark: relaceDark, light: relaceLight },
  'replicate-brand': { dark: replicateBrandDark, light: replicateBrandLight },
  'sensenova-brand-color': {
    dark: sensenovaBrandColorDark,
    light: sensenovaBrandColorLight,
  },
  'spark-color': { dark: sparkColorDark, light: sparkColorLight },
  'stability-color': { dark: stabilityColorDark, light: stabilityColorLight },
  'stepfun-color': { dark: stepfunColorDark, light: stepfunColorLight },
  'together-brand-color': {
    dark: togetherBrandColorDark,
    light: togetherBrandColorLight,
  },
  'upstage-color': { dark: upstageColorDark, light: upstageColorLight },
  'wenxin-color': { dark: wenxinColorDark, light: wenxinColorLight },
  xai: { dark: xaiDark, light: xaiLight },
  xiaomimimo: { dark: xiaomimimoDark, light: xiaomimimoLight },
  'yi-color': { dark: yiColorDark, light: yiColorLight },
  zai: { dark: zaiDark, light: zaiLight },
  'zhipu-color': { dark: zhipuColorDark, light: zhipuColorLight },
}
