package oauth

import (
	"regexp"
	"strings"
	"testing"
)

// OAuth state tokens are generated by CreateSession via randomBase64URL(24).
// These tests verify the security-relevant properties of the state token:
// bulk uniqueness (collision resistance) and format (base64url, no padding).

// base64urlCharsetRegex matches only characters in the URL-safe base64
// alphabet (A-Z, a-z, 0-9, -, _) with no padding (=).
var base64urlCharsetRegex = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

func TestStateToken_Format_IsBase64URLNoPadding(t *testing.T) {
	store := NewMemoryOAuthSessionStore()
	for i := 0; i < 256; i++ {
		rec, err := store.Create(CreateSessionInput{
			Provider:   "codex",
			RedirectURI: "http://localhost:1455/callback",
		})
		if err != nil {
			t.Fatalf("create session %d: %v", i, err)
		}
		if !base64urlCharsetRegex.MatchString(rec.State) {
			t.Errorf("state %q contains non-base64url characters", rec.State)
		}
		if strings.Contains(rec.State, "=") {
			t.Errorf("state %q should not contain padding", rec.State)
		}
		if len(rec.State) != 32 {
			t.Errorf("state length = %d, want 32 (24 bytes → base64url)", len(rec.State))
		}
	}
}

func TestStateToken_BulkUniqueness_NoCollisions(t *testing.T) {
	// Generate a large batch of state tokens and assert no duplicates.
	// randomBase64URL uses crypto/rand with 24 bytes (192 bits of entropy),
	// so collisions should be astronomically unlikely. This is a smoke test
	// for the RNG — a collision here would indicate a broken seeding path.
	store := NewMemoryOAuthSessionStore()
	const sampleSize = 4096
	seen := make(map[string]struct{}, sampleSize)
	for i := 0; i < sampleSize; i++ {
		rec, err := store.Create(CreateSessionInput{
			Provider:   "codex",
			RedirectURI: "http://localhost:1455/callback",
		})
		if err != nil {
			t.Fatalf("create session %d: %v", i, err)
		}
		if _, dup := seen[rec.State]; dup {
			t.Fatalf("state collision detected at iteration %d: %q", i, rec.State)
		}
		seen[rec.State] = struct{}{}
	}
}

func TestStateToken_AndCodeVerifier_AreIndependent(t *testing.T) {
	// State and CodeVerifier are generated by the same randomBase64URL helper
	// but with different byte lengths (24 vs 48). They must both be unique
	// and must not be equal to each other.
	store := NewMemoryOAuthSessionStore()
	const sampleSize = 256
	for i := 0; i < sampleSize; i++ {
		rec, err := store.Create(CreateSessionInput{
			Provider:   "codex",
			RedirectURI: "http://localhost:1455/callback",
		})
		if err != nil {
			t.Fatalf("create session %d: %v", i, err)
		}
		if rec.State == rec.CodeVerifier {
			t.Errorf("state and codeVerifier must never be equal (iteration %d)", i)
		}
		if len(rec.State) >= len(rec.CodeVerifier) {
			t.Errorf("state (%d bytes) should be shorter than codeVerifier (%d bytes) at iteration %d",
				len(rec.State), len(rec.CodeVerifier), i)
		}
	}
}

func TestRandomBase64URL_EmptyInputReturnsEmpty(t *testing.T) {
	// n=0 should yield an empty string with no error.
	got, err := randomBase64URL(0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "" {
		t.Errorf("n=0 should yield empty string, got %q", got)
	}
}

func TestRandomBase64URL_LengthEncoding(t *testing.T) {
	// base64.RawURLEncoding: every 3 input bytes → 4 output chars, no padding.
	// So n bytes → ceil(n*4/3) chars, but RawURLEncoding rounds up to the
	// nearest multiple of 4 only when there's a remainder — actually it
	// produces exactly ceil(n*4/3) chars for n%3 != 0 without padding.
	tests := []struct {
		n          int
		wantMinLen int
		wantMaxLen int
	}{
		{1, 2, 2},    // 1 byte → 2 chars
		{3, 4, 4},    // 3 bytes → 4 chars
		{24, 32, 32}, // 24 bytes → 32 chars (state token length)
		{48, 64, 64}, // 48 bytes → 64 chars (verifier length)
	}
	for _, tc := range tests {
		got, err := randomBase64URL(tc.n)
		if err != nil {
			t.Fatalf("randomBase64URL(%d): %v", tc.n, err)
		}
		if len(got) < tc.wantMinLen || len(got) > tc.wantMaxLen {
			t.Errorf("randomBase64URL(%d) length = %d, want [%d,%d]",
				tc.n, len(got), tc.wantMinLen, tc.wantMaxLen)
		}
	}
}

func TestRandomBase64URL_DifferentCallsAreDifferent(t *testing.T) {
	// Two successive calls must produce different outputs (RNG is seeded).
	a, _ := randomBase64URL(48)
	b, _ := randomBase64URL(48)
	if a == b {
		t.Fatal("two successive randomBase64URL(48) calls produced the same output")
	}
}
